# Generated by Django 4.2.3 on 2023-10-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFestival', models.CharField(max_length=200, unique=True)),
                ('logoFestival', models.CharField(max_length=400, unique=True)),
                ('descriptionFestival', models.TextField(max_length=2500)),
                ('siteWebFestival', models.URLField(max_length=300, unique=True)),
                ('youtubeFestival', models.URLField(max_length=300, unique=True)),
                ('facebookFestival', models.URLField(max_length=300, unique=True)),
                ('instagramFestival', models.URLField(max_length=300, unique=True)),
                ('mentionsLegales', models.TextField(max_length=2000)),
                ('policeEcriture', models.CharField(max_length=200)),
                ('couleurPrincipale', models.CharField(max_length=30)),
                ('couleurSecondaire', models.CharField(max_length=30)),
                ('couleurBackground', models.CharField(max_length=30)),
            ],
        ),
    ]
