// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import  'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA84C9_DA_8mCRcWGHHQDXQinDrjbkjg6s',
    appId: '1:688319085109:web:720d1d383b6fb6218c8f7c',
    messagingSenderId: '688319085109',
    projectId: 'iut-astrolabe',
    authDomain: 'iut-astrolabe.firebaseapp.com',
    storageBucket: 'iut-astrolabe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdf-Ef-PVcP0YtY5elC6pVPS3m1hbXUr0',
    appId: '1:688319085109:android:4c5603a1fcf570ea8c8f7c',
    messagingSenderId: '688319085109',
    projectId: 'iut-astrolabe',
    storageBucket: 'iut-astrolabe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa3AifK1t9Blr7zNLY5x2H7Upy2Cj5lN0',
    appId: '1:688319085109:ios:9050210f6a04a3518c8f7c',
    messagingSenderId: '688319085109',
    projectId: 'iut-astrolabe',
    storageBucket: 'iut-astrolabe.appspot.com',
    iosBundleId: 'com.example.astrolabeUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa3AifK1t9Blr7zNLY5x2H7Upy2Cj5lN0',
    appId: '1:688319085109:ios:48a187097da7abc28c8f7c',
    messagingSenderId: '688319085109',
    projectId: 'iut-astrolabe',
    storageBucket: 'iut-astrolabe.appspot.com',
    iosBundleId: 'com.example.astrolabeUser.RunnerTests',
  );
}
