# Generated by Django 4.2.6 on 2023-10-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0002_modification_partenaire_artiste_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationfestival',
            name='mode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
