# Generated by Django 4.2.6 on 2023-10-26 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='date_modif_news',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_artiste',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_config',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_partenaire',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_performance',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_scene',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
