# Generated by Django 4.2.6 on 2023-11-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0004_modification_news_policeecriture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfestival',
            name='video_promo',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
