# Generated by Django 4.2.6 on 2023-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0005_alter_configurationfestival_video_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfestival',
            name='logoFestival',
            field=models.FileField(max_length=254, unique=True, upload_to='model/configuration/logo/'),
        ),
    ]
