# Generated by Django 4.2.6 on 2023-11-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0006_alter_configurationfestival_logofestival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfestival',
            name='video_promo',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='model/configuration/video/'),
        ),
    ]
