# Generated by Django 4.2.6 on 2023-11-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0007_alter_configurationfestival_video_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfestival',
            name='logoFestival',
            field=models.FileField(unique=True, upload_to='model/configuration/logo/'),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='video_promo',
            field=models.FileField(blank=True, null=True, upload_to='model/configuration/video/'),
        ),
    ]
