# Generated by Django 4.2.6 on 2023-11-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0009_alter_configurationfestival_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfestival',
            name='logoFestival',
            field=models.FileField(unique=True, upload_to='static/model/configuration/logo/'),
        ),
    ]
