# Generated by Django 4.2.6 on 2023-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0010_alter_configurationfestival_logofestival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/model/artistes/'),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='logoFestival',
            field=models.ImageField(unique=True, upload_to='static/model/configuration/logo/'),
        ),
    ]
