# Generated by Django 4.2.6 on 2023-11-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0011_alter_artiste_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfestival',
            name='video_promo',
            field=models.FileField(blank=True, null=True, upload_to='static/model/configuration/video/'),
        ),
    ]
