# Generated by Django 4.2.6 on 2023-11-08 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0004_modification_news_policeecriture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfestival',
            name='video_promo',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='logoFestival',
            field=models.FileField(max_length=254, unique=True, upload_to='model/configuration/logo/'),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='video_promo',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='model/configuration/video/'),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='logoFestival',
            field=models.FileField(unique=True, upload_to='model/configuration/logo/'),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='video_promo',
            field=models.FileField(blank=True, null=True, upload_to='model/configuration/video/'),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='mode',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='logoFestival',
            field=models.FileField(unique=True, upload_to='static/model/configuration/logo/'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/model/artistes/'),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='logoFestival',
            field=models.ImageField(unique=True, upload_to='static/model/configuration/logo/'),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='video_promo',
            field=models.FileField(blank=True, null=True, upload_to='static/model/configuration/video/'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='banniere',
            field=models.ImageField(max_length=254, unique=True, upload_to='static/model/partenaires/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='corps',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(max_length=254, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='banniere',
            field=models.ImageField(unique=True, upload_to='static/model/partenaires/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/model/scenes/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(max_length=254, upload_to='static/model/news'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_artiste',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_config',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_news',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_partenaire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_performance',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date_modif_scene',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='image',
            field=models.ImageField(default='static/model/artistes/default.jpg', unique=True, upload_to='static/model/artistes/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='image',
            field=models.ImageField(default='static/model/scenes/default.jpg', unique=True, upload_to='static/model/scenes/'),
        ),
    ]
