# Generated by Django 4.2.3 on 2023-10-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('site_web', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFestival', models.CharField(max_length=200, unique=True)),
                ('logoFestival', models.CharField(max_length=400, unique=True)),
                ('descriptionFestival', models.TextField(max_length=2500)),
                ('siteWebFestival', models.URLField(max_length=300, unique=True)),
                ('youtubeFestival', models.URLField(max_length=300, unique=True)),
                ('facebookFestival', models.URLField(max_length=300, unique=True)),
                ('instagramFestival', models.URLField(max_length=300, unique=True)),
                ('mentionsLegales', models.TextField(max_length=2000)),
                ('policeEcriture', models.CharField(max_length=200)),
                ('couleurPrincipale', models.CharField(max_length=30)),
                ('couleurSecondaire', models.CharField(max_length=30)),
                ('couleurBackground', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('artistes', models.ManyToManyField(to='API_festivals.artiste')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_festivals.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('artistes', models.ManyToManyField(to='API_festivals.artiste')),
            ],
        ),
    ]
