# Generated by Django 4.2.3 on 2023-10-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=254)),
                ('banniere', models.CharField(max_length=254, unique=True)),
                ('site', models.URLField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='artiste',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='API_festivals.artiste'),
        ),
        migrations.AddField(
            model_name='configurationfestival',
            name='video_promo',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='facebookFestival',
            field=models.URLField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='instagramFestival',
            field=models.URLField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='logoFestival',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='mentionsLegales',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='siteWebFestival',
            field=models.URLField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='youtubeFestival',
            field=models.URLField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.AddField(
            model_name='configurationfestival',
            name='partenaires',
            field=models.ManyToManyField(to='API_festivals.partenaire'),
        ),
    ]
