# Generated by Django 4.2.6 on 2023-10-27 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0003_configurationfestival_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modif_artiste', models.DateField(default=datetime.date.today)),
                ('date_modif_performance', models.DateField(default=datetime.date.today)),
                ('date_modif_scene', models.DateField(default=datetime.date.today)),
                ('date_modif_config', models.DateField(default=datetime.date.today)),
                ('date_modif_partenaire', models.DateField(default=datetime.date.today)),
                ('date_modif_news', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=254)),
                ('corps', models.CharField(max_length=254)),
                ('image', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='configurationfestival',
            name='policeEcriture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_festivals.policeecriture'),
        ),
    ]
