# Generated by Django 4.2.6 on 2023-12-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0007_modification_date_modif_tags_news_date_scene_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='image',
            field=models.ImageField(default='static/model/default.jpg', unique=True, upload_to='static/model/artistes/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='static/model/default.jpg', max_length=254, upload_to='static/model/news'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='image',
            field=models.ImageField(default='static/model/default.jpg', unique=True, upload_to='static/model/scenes/'),
        ),
    ]
