# Generated by Django 4.2.6 on 2023-12-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0007_modification_date_modif_tags_news_date_scene_lieu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='couleurBackground',
            new_name='couleur_background',
        ),
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='couleurPrincipale',
            new_name='couleur_principale',
        ),
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='couleurSecondaire',
            new_name='couleur_secondaire',
        ),
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='descriptionFestival',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='facebookFestival',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='instagramFestival',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='mentionsLegales',
            new_name='mentions_legales',
        ),
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='nomFestival',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='policeEcriture',
            new_name='police_ecriture',
        ),
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='siteWebFestival',
            new_name='site_web',
        ),
        migrations.RenameField(
            model_name='configurationfestival',
            old_name='youtubeFestival',
            new_name='youtube',
        ),
        migrations.RemoveField(
            model_name='configurationfestival',
            name='logoFestival',
        ),
        migrations.AddField(
            model_name='configurationfestival',
            name='logo',
            field=models.ImageField(default='static/model/default.jpg', upload_to='static/model/configuration/logo/'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='image',
            field=models.ImageField(default='static/model/artistes/default.jpg', upload_to='static/model/artistes/'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='image',
            field=models.ImageField(default='static/model/scenes/default.jpg', upload_to='static/model/scenes/'),
        ),
    ]
