# Generated by Django 4.2.6 on 2024-01-24 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_festivals', '0009_alter_artiste_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationfestival',
            name='artistes',
            field=models.ManyToManyField(to='API_festivals.artiste'),
        ),
        migrations.AddField(
            model_name='configurationfestival',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2024, 1, 24, 12, 19, 54, 494621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='configurationfestival',
            name='date_fin',
            field=models.DateField(default=datetime.datetime(2024, 1, 25, 12, 19, 54, 494621, tzinfo=datetime.timezone.utc)),
        ),
    ]
